
[mcp_servers.github]
url = "https://api.githubcopilot.com/mcp"
bearer_token_env_var = "GITHUB_API_TOKEN"

[mcp_servers.github.tools.create_pull_request]
approval_mode = "approve"

[mcp_servers.github.tools.pull_request_review_write]
approval_mode = "approve"

[mcp_servers.github.tools.issue_write]
approval_mode = "approve"

[mcp_servers.github.tools.update_pull_request]
approval_mode = "approve"

[mcp_servers.github.tools.add_issue_comment]
approval_mode = "approve"

[mcp_servers.github.tools.sub_issue_write]
approval_mode = "approve"

[mcp_servers.github.tools.merge_pull_request]
approval_mode = "approve"

[mcp_servers.github.tools.add_comment_to_pending_review]
approval_mode = "approve"

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"

[mcp_servers.openaiDeveloperDocs.tools.search_openai_docs]
approval_mode = "approve"

[mcp_servers.openaiDeveloperDocs.tools.fetch_openai_doc]
approval_mode = "approve"

[mcp_servers.playwright]
args = ["@playwright/mcp@latest"]
command = "npx"

[mcp_servers.playwright.tools.browser_navigate]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_evaluate]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_click]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_resize]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_press_key]
approval_mode = "approve"
