services:
  praxrr:
    image: ghcr.io/yandy-r/praxrr:v2
    container_name: praxrr-prod
    restart: unless-stopped
    ports:
      - '6969:6868'
    volumes:
      - ./config:/config
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - UMASK=022
      - TZ=Etc/UTC
      # - PORT=6868
      # - HOST=0.0.0.0
      - PARSER_HOST=parser
      - PARSER_PORT=5000
      # - AUTH=off
      - PRAXRR_DEFAULT_DB_URL=https://github.com/${PRAXRR_DEFAULT_DB_GIT_USER_NAME}/praxrr-db
      - PRAXRR_DEFAULT_DB_BRANCH=dev
      - PRAXRR_DEFAULT_DB_NAME=Praxrr-db
      - PRAXRR_DEFAULT_DB_TOKEN=${PRAXRR_DEFAULT_DB_TOKEN}
      - PRAXRR_DEFAULT_DB_GIT_USER_NAME=${PRAXRR_DEFAULT_DB_GIT_USER_NAME}
      - PRAXRR_DEFAULT_DB_GIT_EMAIL=${PRAXRR_DEFAULT_DB_GIT_EMAIL}
      - PRAXRR_SCHEMA_REF=v2
    depends_on:
      parser:
        condition: service_healthy

  # Optional - only needed for CF/QP testing features
  parser:
    image: ghcr.io/yandy-r/praxrr-parser:v2
    container_name: praxrr-parser
    restart: unless-stopped
    expose:
      - '5000'
