/**
 * Quality Goals — intent-to-implementation bridge (issue #20).
 *
 * Pure, versioned contracts for the goals translation engine. This module holds only types,
 * enumerations, and static metadata — no logic, no I/O, no runtime/DB imports (the sole exception
 * is a type-only import of {@link UpdateScoringInput}, the shape the engine emits). It is therefore
 * safe to import from client and server alike, mirroring the `$shared/narration` precedent.
 *
 * The engine translates a user's high-level intent (a preset + slider weights) into concrete
 * custom-format scores + quality-profile thresholds — a standard {@link UpdateScoringInput} that
 * flows through the existing `buildScoringOps`/`updateScoring` op path. It never becomes a parallel
 * scoring system.
 */

import type { UpdateScoringInput } from '$pcd/entities/qualityProfiles/scoring/update.ts';
import type { OrderedItem } from '$shared/pcd/display.ts';
import type { GoalQualityFact, GoalQualityLadder } from './ladder.ts';

/**
 * Stamped onto every {@link GoalPlan} and persisted binding. Bump whenever the classifier rules,
 * the closed {@link GoalCategory} set, the policy magnitudes, or the threshold formulas change, so
 * a client can detect that a bound profile was generated by a different engine generation.
 */
export const GOALS_ENGINE_VERSION = '2';

/** Arr apps the engine can APPLY to in this slice. Lidarr is classified but not applied. */
export type GoalArrType = 'radarr' | 'sonarr';

/** The 4 built-in presets. */
export type GoalPresetId = 'best-quality' | 'smallest-size' | 'balanced' | '4k-hdr-priority';

/**
 * Closed, versioned set of semantic categories a custom format can be classified into. Adding,
 * removing, or renaming a member is a breaking change — bump {@link GOALS_ENGINE_VERSION}.
 * `null` (uncategorized) is represented outside this union.
 */
export type GoalCategory =
  | 'unwanted'
  | 'hdr_dv'
  | 'hdr_hdr10plus'
  | 'hdr_baseline'
  | 'remux'
  | 'release_group_tier_1'
  | 'release_group_tier_2'
  | 'release_group_tier_3'
  | 'audio_lossless'
  | 'audio_advanced'
  | 'audio_baseline'
  | 'streaming_service'
  | 'movie_version'
  | 'repack_proper'
  | 'resolution';

/** Every category, in classifier evaluation order. */
export const GOAL_CATEGORIES: readonly GoalCategory[] = [
  'unwanted',
  'hdr_dv',
  'hdr_hdr10plus',
  'hdr_baseline',
  'release_group_tier_1',
  'release_group_tier_2',
  'release_group_tier_3',
  'remux',
  'audio_lossless',
  'audio_advanced',
  'audio_baseline',
  'streaming_service',
  'movie_version',
  'repack_proper',
  'resolution'
] as const;

/** Slider axes. Four are signed weights `[-1, 1]`; `unwantedStrictness` is one-directional `[0, 1]`. */
export type GoalWeightAxisKey = 'qualityVsSize' | 'compatibility' | 'hdrPreference' | 'unwantedStrictness';

/** The resolution ceiling is a discrete enum, not a weight. */
export type GoalResolutionCeiling = '720p' | '1080p' | '2160p';

export const GOAL_RESOLUTION_CEILINGS: readonly GoalResolutionCeiling[] = ['720p', '1080p', '2160p'] as const;

/**
 * The resolved set of slider positions. Weight axes are integers `0..100`; `resolutionCeiling` is an
 * enum. Preset defaults + user edits both produce this shape.
 */
export interface GoalWeights {
  qualityVsSize: number;
  compatibility: number;
  hdrPreference: number;
  unwantedStrictness: number;
  resolutionCeiling: GoalResolutionCeiling;
}

/** UI metadata for one slider axis, served by the presets endpoint so the editor hardcodes nothing. */
export interface GoalAxisMeta {
  key: GoalWeightAxisKey | 'resolutionCeiling';
  label: string;
  kind: 'weight' | 'strictness' | 'ceiling';
  min?: number;
  max?: number;
  step?: number;
  options?: readonly GoalResolutionCeiling[];
  description: string;
}

/** Static, ordered slider metadata for the editor. */
export const SLIDER_AXES: readonly GoalAxisMeta[] = [
  {
    key: 'qualityVsSize',
    label: 'Quality vs Size',
    kind: 'weight',
    min: 0,
    max: 100,
    step: 1,
    description:
      'Favor small, efficient encodes (0) or maximum-fidelity remux/lossless (100). Scales remux, lossless audio, and release-group-tier rewards, and raises the upgrade-until ceiling.'
  },
  {
    key: 'compatibility',
    label: 'Device Compatibility',
    kind: 'weight',
    min: 0,
    max: 100,
    step: 1,
    description:
      'Penalize hardware-demanding formats (Dolby Vision, object-based audio) in favor of widely-playable releases. Higher values steer toward streaming-friendly, broadly-compatible sources.'
  },
  {
    key: 'hdrPreference',
    label: 'HDR Preference',
    kind: 'weight',
    min: 0,
    max: 100,
    step: 1,
    description:
      'How strongly to reward HDR formats (Dolby Vision, HDR10+, HDR10). Has no effect on non-HDR custom formats.'
  },
  {
    key: 'unwantedStrictness',
    label: 'Unwanted Strictness',
    kind: 'strictness',
    min: 0,
    max: 100,
    step: 1,
    description:
      'How aggressively to reject unwanted releases. Raises the minimum-score floor so releases that only match penalized (banned) formats are rejected outright.'
  },
  {
    key: 'resolutionCeiling',
    label: 'Resolution Ceiling',
    kind: 'ceiling',
    options: GOAL_RESOLUTION_CEILINGS,
    description:
      'The highest resolution you want. Formats above the ceiling are demoted; at/below the ceiling are rewarded. It also reshapes the quality ladder: qualities at/below the ceiling are enabled, qualities above it are disabled, and the cutoff is set to the ceiling.'
  }
] as const;

/**
 * Profile-independent facts about one custom format, materialized from the PCD cache. Tags arrive
 * as stored (Title-Case) and are lowercased by the classifier before matching.
 */
export interface CfFacts {
  name: string;
  description: string | null;
  tags: string[];
}

/** Where the ceiling gate placed a CF relative to the chosen resolution ceiling. */
export type GoalCeilingRelation = 'above' | 'match' | 'below';

/** One additive term of a score, for transparent "base +700, quality-favored +700" rendering. */
export interface GoalAxisContribution {
  axis: GoalWeightAxisKey;
  delta: number;
}

/** Machine-readable, narration-ready rationale for one emitted score. */
export interface GoalReason {
  /** Stable code, e.g. `category.remux` or `rule.fallback.no-match`. */
  code: string;
  category: GoalCategory | null;
  ruleId: string;
  base: number;
  axisContributions: GoalAxisContribution[];
  ceiling: GoalCeilingRelation | null;
}

/** One scored custom format in the plan. */
export interface GoalCfDecision {
  customFormatName: string;
  arrType: GoalArrType;
  category: GoalCategory;
  score: number;
  reason: GoalReason;
}

/** A custom format the classifier could not place; excluded from the scoring input (never mis-scored). */
export interface GoalUncategorizedCf {
  name: string;
  /** Advisory, clearly-unvalidated best guess from the tag signal, or null. */
  suggestedCategory: GoalCategory | null;
  reason: string;
}

/** Coverage split for the transparency surface. */
export interface GoalCoverage {
  total: number;
  scored: number;
  uncategorized: number;
}

export interface GoalThresholds {
  minimumScore: number;
  upgradeUntilScore: number;
  upgradeScoreIncrement: number;
}

/** Input to the engine. Materialized by the route; the engine touches no DB. */
export interface ComputeGoalPlanInput {
  arrType: GoalArrType;
  weights: GoalWeights;
  presetBaseUpgrade: number;
  customFormats: CfFacts[];
  /**
   * Per-arr quality facts (name + resolution) materialized from `quality_api_mappings` + `QUALITIES`.
   * Optional so pure CF-only tests need not thread them; absent → no ladder change.
   */
  qualityFacts?: GoalQualityFact[];
  /** The profile's current `quality_profile_qualities` rows; absent → no ladder change. */
  currentLadder?: OrderedItem[];
  /** True when the profile is also compatible with a sibling arr (drives the shared-ladder advisory). */
  compatibleWithSiblingArr?: boolean;
}

/** The engine's deterministic output. */
export interface GoalPlan {
  engineVersion: string;
  arrType: GoalArrType;
  decisions: GoalCfDecision[];
  uncategorized: GoalUncategorizedCf[];
  thresholds: GoalThresholds;
  coverage: GoalCoverage;
  /** Ready for `buildScoringOps`; scores use an explicit arrType, never `'all'`. */
  scoringInput: UpdateScoringInput;
  /**
   * Internal desired quality ladder (analogue of `scoringInput`), consumed by the shared op builder
   * for preview + apply. `null` when the ceiling produces no ladder change for this profile.
   */
  ladderInput: { orderedItems: OrderedItem[] } | null;
  /** Wire-exposed presentational ladder + cutoff for the always-shown generated-config surface. */
  qualityLadder: GoalQualityLadder;
}

/** Per-CF score delta between two plans, powering the slider goal-diff. */
export interface GoalScoreDelta {
  customFormatName: string;
  from: number | null;
  to: number | null;
  delta: number;
}

export interface GoalThresholdDelta {
  field: keyof GoalThresholds;
  from: number;
  to: number;
}

/** Pure diff between two goal plans (e.g. before/after moving a slider). */
export interface GoalDiff {
  scoreChanges: GoalScoreDelta[];
  thresholdChanges: GoalThresholdDelta[];
}
