#!/usr/bin/env bash
# go-tools.sh
# Generate .golangci.yml with sensible defaults. Invoked by init-formatters.sh.
#
# Usage: go-tools.sh [target-dir] --generate
#
# Env overrides:
#   GO_TOOLS_FORCE        (true|false)
#   GO_TOOLS_ASSUME_YES   (true|false)
#   GO_TOOLS_DRY_RUN      (true|false)

set -euo pipefail

force="${GO_TOOLS_FORCE:-false}"
assume_yes="${GO_TOOLS_ASSUME_YES:-false}"
dry_run="${GO_TOOLS_DRY_RUN:-false}"

target="${1:-}"
action="${2:-}"

if [[ -z "$target" || "$target" == "--generate" ]]; then
    action="${target:-$action}"
    target="$PWD"
fi

if [[ "$action" != "--generate" ]]; then
    echo "[go-tools] usage: go-tools.sh [target-dir] --generate" >&2
    exit 1
fi

if [[ ! -d "$target" ]]; then
    echo "[go-tools] target not a directory: $target" >&2
    exit 1
fi

dest="$target/.golangci.yml"

if [[ -e "$dest" ]]; then
    if [[ "$force" != "true" ]]; then
        if [[ "$assume_yes" == "true" ]]; then
            echo "[go-tools] keeping existing $dest"
            exit 0
        fi
        read -r -p "Overwrite existing $dest? [y/N] " response
        if [[ ! "$response" =~ ^[Yy]$ ]]; then
            echo "[go-tools] keeping existing $dest"
            exit 0
        fi
    fi
fi

if [[ "$dry_run" == "true" ]]; then
    echo "[go-tools] [dry-run] would write $dest"
    exit 0
fi

cat > "$dest" <<'YAML'
# Generated by go-tools.sh --generate
# Docs: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: ""

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  # Canonical well-known paths — keep aligned with
  # scripts/bundle/lib/excludes.sh (STYLE_EXCLUDES).
  exclude-dirs:
    - node_modules
    - target
    - build
    - dist
    - out
    - coverage
    - vendor
    - .venv
    - venv
    - env
    - __pycache__
    - .mypy_cache
    - .pytest_cache
    - .ruff_cache
    - .next
    - .nuxt
    - .cache
    - .terraform
    - .cursor-plugin
    - .codex-plugin
    - .opencode-plugin
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
YAML

echo "[go-tools] wrote $dest"
exit 0
