import './arrUpgrade.ts';
import './arrRename.ts';
import './arrSync.ts';
import './arrPullStartup.ts';
import './pcdSync.ts';
import './trashGuideSync.ts';
import './backupCreate.ts';
import './backupCleanup.ts';
import './logsCleanup.ts';
