name: Lint

on:
  pull_request:
  push:
    branches: [main, master]

concurrency:
  group: lint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  lint-shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: ./scripts/install-shellcheck.sh
      - run: ./scripts/style.sh lint --shell

  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npx --yes markdownlint-cli "**/*.md" --ignore-path .markdownlintignore
      - run: npx --yes prettier --check "**/*.{md,mdx,json,jsonc,yaml,yml}" --ignore-path .prettierignore