name: Lint

on:
  pull_request:
  push:
    branches: [main, master]

concurrency:
  group: lint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Install shellcheck
        run: ./scripts/install-shellcheck.sh
      - run: ./scripts/style.sh lint --shell

  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: lts/*
      - run: npm ci
      - run: npx markdownlint-cli "**/*.md" --ignore-path .markdownlintignore
      - run: npx prettier --check "**/*.{md,mdx,json,jsonc,yaml,yml}" --ignore-path .prettierignore
